name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: "index.html"
          destination_repo: " shahidsarvani/test"
          destination_folder: "folder1"
          user_email: "hamza0952454@gmail.com"
          user_name: "HamzaZafarBhatti"
          commit_message: "copying file"
